### PR TITLE
Check for required packages

### PR DESCRIPTION
**Pull request by yorek**
Added logic to check for required packages, and updated documentation

### CODE REVIEW

**Comment by yorek** [comment]
To fix issue #5

**Comment by zhixingr** [comment]
The fix works. But if you just want to get the correct error message to indicate that the required packages couldn't be loaded, the easy fix is to just add library("zoo") and library("plyr") in the beginning of the R script. So we don't need write a separate script and update the powershell script.

Thanks,
Zhixing

**Comment by jakubpizon** [comment]
Hi All,

I try to run data_labeling.sql script and even I got all packages intalled I still do not get any result.

The only thing I get is error command like:

Msg 201, Level 16, State 4, Procedure data_labeling, Line 0 [Batch Start Line 2]
Procedure or function 'data_labeling' expects parameter '@dataset_type', which was not supplied.

**Comment by DataIntelytics** [comment]
While I cannot see your .sql file, the error message seems pretty clear... you're missing your passed parameter of @dataset_type. Best of luck!

**Pull request merged**
